/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class weka_attributeSelection_CMIMAttributeEvaluator */

#ifndef _Included_weka_attributeSelection_CMIMAttributeEvaluator
#define _Included_weka_attributeSelection_CMIMAttributeEvaluator
#ifdef __cplusplus
extern "C" {
#endif
#undef weka_attributeSelection_CMIMAttributeEvaluator_serialVersionUID
#define weka_attributeSelection_CMIMAttributeEvaluator_serialVersionUID 2091705669885950849i64
#undef weka_attributeSelection_CMIMAttributeEvaluator_serialVersionUID
#define weka_attributeSelection_CMIMAttributeEvaluator_serialVersionUID 1i64
/*
 * Class:     weka_attributeSelection_CMIMAttributeEvaluator
 * Method:    _process
 * Signature: (Lweka/core/Instances;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_weka_attributeSelection_CMIMAttributeEvaluator__1process
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
